[".config/bat/themes/Catppuccin Mocha.tmTheme"]
type = "file"
url = "https://raw.githubusercontent.com/catppuccin/bat/refs/heads/main/themes/Catppuccin%20Mocha.tmTheme"
refreshPeriod = "168h"
[".tmux/plugins/tpm"]
type = "git-repo"
url = "https://github.com/tmux-plugins/tpm.git"
